debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: ckwldlsTest!1@2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
#  h2.console.enabled: false
#  sql:
#    init:
#      mode: always


#---
#
#spring:
#  config:
#    activate:
#      on-profile:
#        - testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driverClassName: org.h2.Driver
#  sql:
#    init:
#      mode: always
#  test.database.replace: none


